### ISSUE TITLE
Glitchy nether generation (possibly BoP related)

### ISSUE THREAD

**Issue by Tonius** [progwml6/Natura#149]
I have noticed Natura worldgen is quite glitchy in the Nether. The features like clouds, mushrooms and trees seem to disregard what is in the way when generating, causing them to spawn partly or completely inside walls or floors.

This happens at least with Biomes O' Plenty installed. I haven't tested it with the vanilla Nether yet. I have also noticed that Ghostwood trees and Tainted Soil don't spawn.

Again, this may be Biomes O' Plenty messing things up. Just thought I'd report it anyway.

**Comment by Sinhika** [comment]
My guess is that the fundamental problem between BOP and Natura is that Natura's nether gneration is a hack that completely hijacks Nether dimension generation and is unaware of Nether biomes--so, BOP nether biomes, which (properly) interface with standard nether generation, never call the horrible hack that is Natura's nether generation.   Thus no heat sand or tainted soil in BOP-generated nether.

I do not envy progwml6 the joy of re-writing Natura's nether gen code.  I have idly wondered if it would work better for mod interoperability to scrap Natura's hack and use the ore-gen hooks to add tainted soil and heatsand. I assume the flora is handled by standard decoration hooks, since they do appear in BOP nether biomes.

**Comment by progwml6** [comment]
Thus the reason that the entire worldgen system is getting redone in 1.8

**Comment by Sinhika** [comment]
I thought you might be. Good luck; that's some heavy lifting you're doing there. I've looked at some of that code.

**Comment by alexbegt** [comment]
Heavy lifting i'm doing :P

**Comment by Sinhika** [comment]
I'd offer to help, but between a full-time programming job and maintaining my mods and akkamaddi's old mods, I'm pretty booked up. However, if you ever get stuck and need fresh eyes or just want a code review, send me a message.

**Comment by progwml6** [comment]
worldgen is getting added this week in the https://github.com/progwml6/Natura/tree/1.10 branch if anyone has comments on 1.10 issues let us know or file PR's
