### ISSUE TITLE
Aramanth logs (purple) make Eucalyptus planks (pink) in the TE sawmill 

### ISSUE THREAD

**Issue by pjfranke** [progwml6/Natura#234]
An aramanth log (purple) makes 6 eucalyptus planks (pink) in the TE sawmill.

Confirmed via a minimal pack assembled via CurseVoice launcher, with NEI, WAILA, Thermal Expansion and dependencies, and Natura and dependencies.

**Comment by squeek502** [comment]
Caused by "amaranth" not being found in [Planks.textureNames](https://github.com/progwml6/Natura/blob/master/src/main/java/mods/natura/blocks/trees/Planks.java#L23), so findPlankForName("amaranth") returns -1 (which seems like it'd throw an exception). The texture name for amaranth seems to be "purpleheart".

Changing [this line](https://github.com/progwml6/Natura/blob/master/src/main/java/mods/natura/plugins/te4/TE4Pulse.java#L146) to:

```
addWood(NContent.rareTree, 2, "purpleheart");
```

would probably fix it.

**Comment by pjfranke** [comment]
Seems logical to me, good find.
