### ISSUE TITLE
leaves in world are localized as block..NLeaves.name

### ISSUE THREAD

**Issue by yrsegal** [progwml6/Natura#252]
(this is annoying with WAILA)

**Comment by progwml6** [comment]
1.7 is no longer being updated. Feel free to submit a PR.

**Comment by macks2008public** [comment]
I realize this version is no longer supported, but I just wanted to chime in and note that, besides the aforementioned visual/data issue with localizing the name, these incorrectly localized blocks also do not seem to decay normally; I have to break them manually when they occur. they might occur because of different Natura trees spawning too close to each other, but I'm not sure and don't feel like trying to dig into old code to fix it; good luck to anyone that does.
