### ISSUE TITLE
can't get bloodwood sapling to grow in sf3

### ISSUE THREAD

**Issue by DoomSquirter** [progwml6/Natura#313]
playing sky factory 3 on SMP
natura-1.10.2-4.1.0.15

planted at y 80, over nothing but void, 3x3 of netherrack with sapling planted upside down in the middle (couldn't remember what cardinal direction of the 2x2 the sapling had to be at since that was the case back in 1.6.4 days iirc)

bonemealed, twerked, watering can(s), nothing.  

Does it grow at this point in the mod?  if so, what could I be doing wrong?  No reference to verify they exist in the nether since nether is void here.

**Comment by SweetSugarSugar** [comment]
I've had trouble growing fusewood saplings myself in that pack.

**Comment by alexbegt** [comment]
Nether trees are not done, That is why they do not grow. I have not gotten around to fixing them due to school.

**Comment by Gunner76th** [comment]
I understand the constraints that school and reallife can impose, being a medical student myself. Is it not possible for someone else in the dev team to work on this issue instead of @alexbegt since this has now been an issue since September, making this one missing feature of the mod nearly 6 months old?
