### ISSUE TITLE
Seeds don’t have names

### ISSUE THREAD

**Issue by ghost** [progwml6/Natura#328]
http://i.imgur.com/EpVhMSI.png

This happens with other types of seeds from Natura as well.

**Comment by SweetSugarSugar** [comment]
Looks like someone needs to update a lang file.

**Comment by aelfwyne** [comment]
I'm playing on US English, and a lot of the items on Natura are glitching the names out for me as well.

**Comment by ghost** [comment]
By the way, Natura’s seeds do not work well with WAILA/HWYLA. For example, it won’t say the progress of the plants like it does with other types of plants.

**Comment by TheCandiedHat** [comment]
Good to know it's probably a lang file. I'm currently working towards fixing that. I'll be submitting a pull request (with a fix) soon! (Hopefully)

**Comment by TheCandiedHat** [comment]
EDIT: There are no problems (anymore). Maybe the error everyone has been getting has been TConstructs fault? I have a new TConstruct download link that works better. And it's still at the same website!

![screen shot 2017-03-31 at 9 23 19 am](https://cloud.githubusercontent.com/assets/19596980/24557116/c9a3cd32-15f3-11e7-932d-df247ec58382.png)
![screen shot 2017-03-31 at 9 23 08 am](https://cloud.githubusercontent.com/assets/19596980/24557115/c9a31fea-15f3-11e7-9a3b-631ea01e52b5.png)
https://dvs1.progwml6.com/jenkins/job/TConstruct_1.8.9/

EDIT: Pretty sure it's Tinkerers Construct that causing this. TConstruct 1.8.9 works with it, but when I run FTB Beyond 1.2.1 via the Twitch Desktop app (on a Mac running Mac OS Sierra latest version) these happen:

![screen shot 2017-03-31 at 9 35 16 am](https://cloud.githubusercontent.com/assets/19596980/24557606/81b2a1c2-15f5-11e7-86d9-d231673904ff.png)
![screen shot 2017-03-31 at 9 34 03 am](https://cloud.githubusercontent.com/assets/19596980/24557610/81c9566a-15f5-11e7-9b97-7a5d025d3db0.png)
![screen shot 2017-03-31 at 9 34 16 am](https://cloud.githubusercontent.com/assets/19596980/24557612/81cc7156-15f5-11e7-834e-c6ee8e4934c5.png)
![screen shot 2017-03-31 at 9 34 30 am](https://cloud.githubusercontent.com/assets/19596980/24557608/81c5f1d2-15f5-11e7-834a-89258a116ff5.png)
![screen shot 2017-03-31 at 9 35 01 am](https://cloud.githubusercontent.com/assets/19596980/24557611/81c9bbb4-15f5-11e7-93d4-b71aa3f4fcb1.png)
![screen shot 2017-03-31 at 9 35 10 am](https://cloud.githubusercontent.com/assets/19596980/24557609/81c60366-15f5-11e7-8696-4d207d2ded49.png)

This is not an error with Natura, so I vote to have this issue closed. To anyone out there viewing this: The problem is not with Natura, it's with Tinkerers Construct. Get Tinkerers Construct for 1.8.9 (no matter what Minecraft version you are running)

**Comment by TheCandiedHat** [comment]
Possibly the error is in this?
`
@Override
    public ItemStack addMeta(int meta, String name)
    {
        if (!this.states.containsKey(meta))
        {
            throw new RuntimeException("Usage of wrong function. Use the addMeta function that has an amount paired with it with this implementation");
        }

        return super.addMeta(meta, name);
    }
`

**Comment by ghost** [comment]
Thanks, but you might want to just edit your comments rather than triple-post.

**Comment by alexbegt** [comment]
The newest version of Natura has the fixed names, so if you or the pack has a old version, it
won't have the correct names.

**Comment by TheCandiedHat** [comment]
Yes... but there's a problem with TConstruct, Forge, or some other external source causing the problem. The modpack I have uses Natura 4.1.0.24 for Minecraft 1.10.2. It's definitely caused by some external software. Maybe TConstruct, or Mantle.

**Comment by ghost** [comment]
How would Tinkers’ Construct be able to interact with the names of some Natura items? That makes no sense. Tinkers’ Construct doesn’t even have any seed items or any relevance to Natura whatsoever.

**Comment by alexbegt** [comment]
OK, my fault; natura-1.10.2-4.1.0.29 WILL fix the language issues!
