### ISSUE TITLE
compatibility with other mod nether plants

### ISSUE THREAD

**Issue by 0Navis0** [progwml6/Natura#343]
The nether plants like saplings, mushrooms, bushes, flowers.... from other mods like Biomes O Plenty and Ad Inferos can't be placed on tainted soil and heat sand while they should.

**Comment by alexbegt** [comment]
The Blocks from Ad Inferos can't be placed on tainted soil or heat sand because Ad Inferos doesn't check if it can be placed on natura's blocks. As for Biomes O Plenty, I can put their glowshroom's down on Tainted Soil and Heat Sand. If you can, what blocks form Biomes O Plenty can't you place on the Tainted Soil/Heat Sand?

**Comment by 0Navis0** [comment]
The easiest would be I report it directly to the BOP and Ad Inferos modders.

**Comment by 0Navis0** [comment]
Okay here is the list of all the nether plants from BOP and Ad Inferos
- Biome O Plenty
	- Hellbrack tree
	- Devilweed
	- Deadgrass
	- Thorns
	- Burning Blossom
	- Eyebulb
	- Glowshroom
	- Toadstool
	- Blue milk cap
	- Flat Mushroom
	- Portobello
	- Ivy
- Ad Inferos
	- Inferno tree
	- Magma tree
	- Phantom tree
	- Ash tree
	- Purple Mushroom
- NetherEx
	- Brown Elder Mushroom
	- Red Elder Mushroom
	- Enoki Mushroom
	- Thorstalk
