### ISSUE TITLE
Redwood oddities.

### ISSUE THREAD

**Issue by xannor** [progwml6/Natura#413]
None of these issues are major and I have ideas on how to work around some but hey are annoying.

Minecraft: 1.12.2
Natura: 4.3.0.23

1) a 7x7 does not properly grow a tree. I think this is due to a fix you instituted to handle forge grow events. It seems that when a random sapling is picked, something checks that there are a enough saplings to grow a tree, but if there is not a 7x7 around the chosen one, a grid of them will be destroyed and nothing grows. I can work around this by immediately bonemealing the center sapling and so far this has had a 100% success rate, though it does have the side effect of needing to run fast to avoid being stuck in the tree.

2) The tree seems to be very flammable and on a chunk loaded server will burn down over the span of a real day or two due to lightning strikes. I am trying to work around this using Chisel Cloud blocks in a layer near build limit, that I can make pretty at a later time, to hopefully block the lightning.

3) The tree generates with very lovely foliage, however most of it seems to be too far from the tree and so once something ticks off the leaf decay, it will loose most of its leaves, and you are left with a fairly ugly and large stick/bush. I am thinking of just cheating and using a block replace command to replace all of the leaves with "user" placed ones so they don't despawn. I havent tried this yet. The only fix for this I can think of is to figure out a way in the branch generation code of ensuring that bark is close enough to all edges to satisfy the decay code, but I am not famillair with the code to know if that is even a possibility.

Example of decay.
https://imgur.com/a/UR0MS

**Comment by xannor** [comment]
It seems doing a massive fill replace will "save" the tree from decay so I created a gist with the commands to use as a function.
https://gist.github.com/xannor/04123c99d2c1e059bcc8b8fdbdd30fcf

Save this in a subfolder under the worlds data/functions folder.

from the server, or SP, console run /reload to pickup the function.

Then standing at the south edge of the tree, centered, facing north run:
/function _subfolder_:save

this should save most of the tree. In my tests sometimes the very top would not convert from metadata 0 to 4 and I could not figure out why, but it seems to handle most of the tree sizes.

**Comment by Siyaa0** [comment]
I'm also encountering this problem with the redwoods, although I'm playing SF3 so I have a different version of minecraft (1.10.2) and natura (4.1.0.80) Thanks for providing your work-around, @xannor . I'll have to give that a try.

**Comment by Nacoran** [comment]
Having the same problem, except we can't even get them to grow at all.  Maybe a work around would be to have the saplings not work, but then let you combine 49 saplings into one 'mega' sapling that grows?

**Comment by professionalneerdowell** [comment]
I was trying to figure out why my saplings were disappearing and found this issue.  I took a look at the code and I think I know where the heart of the problem lies.  In

/src/main/java/com/progwml6/natura/overworld/block/saplings/BlockRedwoodSapling.java

in checkRedwoodSaplings (line 169 in alexbegt's commit 67a440b on Nov 1, 2017), the code seems to checking if the triggering sapling is the center of the 7x7 square, but it could be any of the saplings in the 7x7 grid, so when a growth even occurs, some of the saplings are identified as part of the spawn, but not necessarily all of them.

Next, after checkRedwoodSaplings is called in generateTree (on line 135), the BaseTreeGenerator is swapped out for a RedwoodTreeGenerator only if enough saplings were found around the generating sapling.

I think the bug lies when replaceBlocksWithAir is called after the switch statement.  It is called regardless of whether or not there were enough saplings present, wiping out some of the saplings if the center sapling wasn't the generating sapling.

I'd suggest moving the replaceBlocksWithAir statement inside the if statement on line 142, after initializing RedwoodTreeGenerator as a possible fix.

**Comment by justinrusso** [comment]
@professionalneerdowell great find 👍 Bone-mealing the center one made it grow, appreciated!

Hopefully this can get fixed

**Comment by sandalle** [comment]
Same issue and fix (quickly bonemeal center sapling) as @xannor .

Minecraft: 1.12.2
Forge Mod Loader: 1.12.2-14.23.2.2654
Natura: 1.12.2-4.3.2.42
Modpack: https://minecraft.curseforge.com/projects/nst-world-of-color v1.0.5

**Comment by Zygus42** [comment]
Number 3 above:
Redwoods generating naturally in the world appear to come in 2 varieties now.  1 variety is the old variety which has little bits of wood all over it and this keeps the leaves where they're meant to be.  The other variety only has the central trunk.  It still has all the leaves and looks good, until you get too close, which is when the bulk of the leaves fall off.  No clue whether this is a bug, something done for testing which was left in or intentional.

![2018-05-28_11 28 15](https://user-images.githubusercontent.com/20757445/40595931-43ad65fc-626a-11e8-904b-bcb3d9842f56.png)

Tested with no mods other than:
natura-1.12.2-4.3.2.49
Mantle-1.12-1.3.2.24
forge-1.12.2-14.23.4.2703-installer-win

Haven't tested this, but I'm guessing that when you grow them you can get either version as well.

**Comment by acook** [comment]
I looked into @professionalneerdowell's suggestion and it does look like it might be the issue. It's not clear to me why those lines are outside the switch statement, naively I assume moving them into the switch and the subsequent `if` statement would fix it but I don't have a java development environment set up to test it right now.

**Comment by ProsperCraft** [comment]
https://github.com/Sunekaer/stoneBlock/issues/173
