### ISSUE TITLE
[1.12.2] Crafting recipes problems

### ISSUE THREAD

**Issue by ghost** [progwml6/Natura#415]
When try to craft for example sticks, buttons, pressure plates from natura wooden planks, are crafted vanilla sticks, buttons, pressure plates instead natura sticks, pressure plates etc.

It looks like recipe part of this mod is broken.

Tested on the 1.12.2, forge 2559, natura 1.12-4.3.0-23, mantle 1.12-1.3.1-21, no others mods present

**Comment by armuell** [comment]
I can confirm this an issue as well, just happened to me (same mc and forge)

**Comment by veronicaalange** [comment]
Confirming as well. It seems that 1.12.2 uses shapeless and shaped recipes that are ore dictionaried now.
for instance:
<minecraft:button> *1, [[<ore:plank_wood>]]
instead of:
<minecraft:button> *1, [[<minecraft:plank_wood>]]

also, crafttweaker does not appear to be able to override or remove these vanilla recipes.

**Comment by Zarepheth** [comment]
Use of the "no more recipe conflicts" mod helps to deal with conflicting recipes. When a recipe from one mod conflicts with another (or vanilla) a button is enabled to cycle through which mod's recipe to use.

But echoing @legracen I used CraftTweaker in an attempt to add a vanilla style recipes for Natura wood fences, but they do not appear in JEI nor do they work in the crafting grids.

**Comment by ghost** [comment]
I prefer fix this mod instead using workaround like craftweaker/no more recpe conflict mod.

**Comment by Frontrider** [comment]
Yeah I would prefer the fix as well. Its not conflicting with an another mod, but vanilla itself.

**Comment by Phonavis** [comment]
While the ore dictionary thing is an issue, the main issue is the mod is using outdated recipes. 

Look at the recipe for vanilla fences, they use the respective woods then normal vanilla sticks, which is how Natura's fences should be rather than the old 1.7.10 way

**Comment by terrapin47** [comment]
Since this hasn't been changed since December, it seems our main alternative is fixing it ourselves with CT.  For anyone who comes across this, I've made a script you can use that fixes the issue.

https://pastebin.com/ZiBtcXrn

Fences/gates use vanilla crafting style, and buttons/plates/crafting tables use any stick as a reusable component to get around the vanilla recipe accepting any planks.  Each section is split out and commented, so if you only want the fence/gate fix you can remove the others, or just use this as a starting point for your own solution.

**Comment by alexbegt** [comment]
https://github.com/progwml6/Natura/commit/b87b6c852777332b5120a32b2839865ac419ceb4 I did change the recipes and a new version has been pushed to curse. It currently is uploading: https://minecraft.curseforge.com/projects/natura/files/2593539 If this bug still exists, Please open a new Ticket!

Thanks,

Alexbegt
